In [1]:
#Question 1

import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)

print("Mean Of The Above Matrix Is =",np.sum(x)/len(x))


#Second Method
print("Mean Of The Above Matrix Is =",np.mean(x))

Formed Matrix Is 
 [[0.99747437]
 [0.71238417]
 [0.37562263]
 [0.40583851]
 [0.03594287]
 [0.08054146]
 [0.97593004]
 [0.85759762]
 [0.62511968]
 [0.4773789 ]]
Mean Of The Above Matrix Is = 0.5543830252109616
Mean Of The Above Matrix Is = 0.5543830252109616


In [2]:
#Question 2

x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)

print("Variance of the formed matrix is =",np.var(x))


print("Standard deviation of the formed matrix is =",np.std(x))
#Second Method For standard deviation
print("Standard deviation of the formed matrix is =",np.sqrt(np.var(x)))

Formed Matrix Is 
 [[0.30275434]
 [0.68630323]
 [0.2241168 ]
 [0.50223161]
 [0.83207099]
 [0.85886321]
 [0.65859073]
 [0.07878134]
 [0.43847086]
 [0.22681101]
 [0.44493311]
 [0.59920326]
 [0.30326991]
 [0.78845033]
 [0.7842998 ]
 [0.51631083]
 [0.10629961]
 [0.6204788 ]
 [0.47191285]
 [0.24560729]]
Variance of the formed matrix is = 0.05579295380965157
Standard deviation of the formed matrix is = 0.23620532129833902
Standard deviation of the formed matrix is = 0.23620532129833902


In [3]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.matmul(A,B)
print("Matrix Formed After Multiplication\n",x)


print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[4.99951498 5.54462652 6.30862135 4.84567865 4.64322802 4.14583377
  4.43415966 4.07997325 5.38354274 2.82316153 5.38331084 5.04276148
  4.98413801 5.37405768 5.24834835 4.6636031  4.75190387 5.11530313
  5.5585246  4.78411493 4.85179413 4.78792113 5.13529403 4.97691291
  5.34755307]
 [5.00201189 4.92747932 5.99925174 4.60216481 4.86477697 4.24137973
  5.03269101 4.05875326 5.71285963 2.86478123 5.13713981 4.71017065
  4.91497872 5.4917001  5.21409737 4.76704467 4.51811061 4.27083051
  5.45553877 3.71901331 5.19924798 4.67801412 4.89382767 4.97448024
  5.28075925]
 [4.27759788 4.04120691 5.78658324 4.5758123  5.39663514 3.34334435
  4.75879978 4.16614162 5.29652892 3.28186535 4.21777774 4.798526
  4.93542661 5.87048079 4.18271103 4.41649869 4.72629227 4.44701121
  5.64485962 4.10621366 5.6864498  4.267332   4.77747392 5.58316554
  5.69929096]
 [4.74129564 3.38533264 5.15464735 4.3512006  5.16373244 2.79166154
  4.38029148 3.54455164 3.87480036 3.307

In [4]:
#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))

[[0.00912664]
 [0.14912759]
 [0.93234071]
 [0.56110739]
 [0.58104703]
 [0.23470724]
 [0.71999509]
 [0.44849597]
 [0.10202067]
 [0.19977953]]



After performing given function
[[0.50228164]
 [0.53721296]
 [0.71754992]
 [0.63670873]
 [0.64130829]
 [0.55840892]
 [0.67260594]
 [0.61028158]
 [0.52548307]
 [0.54977943]]
